### ISSUE TITLE
function getGateway(stdout)

### ISSUE THREAD

**Issue by TascSystems** [FGRibreau/network-config#1]
I found that I was not getting the proper results for getGateway, and while I'm not an expert on lodash, I found this worked in getting me the proper results from my Debian platform:

``` javascript
    return _.chain(stdout)
    .split('\n')    // Split each route line into array
    .filter(function (line) {   // Select only lines with default
            return _.include(line, 'default');
        })
    .first()        // Grab the first line (default)
    .split(' ')     // Split line into array
    .without('')    // Get rid of unneeded array elements
    .rest()         // Get rid of first element (default)
    .first(1)       // Grab the first element afterwards, which should be the gateway
    .value();       // We have our value
```

Result: 

```
name=eth0
ip=10.10.5.112
netmask=255.255.0.0
broadcast=10.10.255.255
mac=00:18:31:91:55:26
gateway=10.10.3.254
```

p.s. I'm just learning git, so I didn't push this to you for approval.

**Comment by FGRibreau** [comment]
Hello @TascSystems !

Ok, next steps are:
- add a fixture of your ifconfig text output inside test/fixtures/
- **add** a test for it inside https://github.com/FGRibreau/network-config/blob/master/test/ifconfig.interfaces.test.js
- change the src/ifconfig.interfaces.js to switch back the test to green state
- create a pull-request for it
- I will merge it :)
