### ISSUE TITLE
Adding DHCP status in summary list

### ISSUE THREAD

**Issue by juancampuzano** [FGRibreau/network-config#15]
Is it posible to show DHCP status in each interface. Something like this:

 [{
    name: 'eth0',
   dhcp: true,
    ip: '1.1.1.77',
    netmask: '1.1.1.0',
    mac: 'aa:aa:aa:aa:aa:aa',
    gateway: '10.10.10.1'
   },
   { ... }, { ... }]
  */

**Comment by FGRibreau** [comment]
why would you want that ? :)

**Comment by juancampuzano** [comment]
Information is no longer needed

**Comment by fjhunter** [comment]
I think this feature could be really cool as well. I created a pull request: https://github.com/FGRibreau/network-config/pull/26
