### ISSUE TITLE
Add support for Kubuntu & Raspbian (ifconfig has different output )

### ISSUE THREAD

**Issue by dnrelectronica** [FGRibreau/network-config#17]
Hi all, 

I try to use the network-config package on a raspberry pi , but it fails directly when i want to show the interfaces. 

The split() functions fails, and this is because the output of ‘ifconfig’ is not the same for different distro’s (KUBUNTU vs RASPBIAN).

Can you make the library compatible with raspberry pi’s ifconfig output??

For the moment i changed the code myself and it worked ok. 

changed file: ifconfig.interface.js

Has anywone a solution for this?

**Comment by FGRibreau** [comment]
> Can you make the library compatible with raspberry pi’s ifconfig output??

Please open a PR and [update the test suite](https://github.com/FGRibreau/network-config/tree/master/test), if it works, I will merge it and release a new version of network-config :+1:

**Comment by dnrelectronica** [comment]
> > Can you make the library compatible with raspberry pi’s ifconfig output??
> 
> Please open a PR and [update the test suite](https://github.com/FGRibreau/network-config/tree/master/test), if it works, I will merge it and release a new version of network-config 👍

i'm sorry i don't understand what i need to do right now? update the test suite???

**Comment by FGRibreau** [comment]
> i'm sorry i don't understand what i need to do right now?

- fork the github project
- create a git branch
- update the code to make it compatible with Kubuntu & Raspbian
- update the test suite code (add tests cases for kubuntu & raspbian)
- run tests to check that everything's alright
- commit
- push
- create a pull-request on github
- done 🎉 :)

**Comment by dnrelectronica** [comment]
So, i have to update your code? i thought you are going to solve this issue?

**Comment by FGRibreau** [comment]
Indeed, I do not have the time right now to do it and you have already fixed it on your computer, why not share it and be part of the open-source community :)

**Comment by dnrelectronica** [comment]
> Indeed, I do not have the time right now to do it and you have already fixed it on your computer, why not share it and be part of the open-source community :)

i changed the code into a form it works for me for raspberry pi, but it breaks now when you use it with a linux desktop distro like ubuntu because the output of 'ifconfig' is different. Kubuntu outputs 'eth0' and raspbian outputs 'eth0:' (with the ':' ).
